### PR TITLE
Add Scala 3 build

### LINKED ISSUE #25: Add Scala 3 build
See: https://github.com/trace4cats/trace4cats/issues/229

### PR DESCRIPTION
**Pull request by catostrophe**
I replaced `circe` with `json4s`. It does not have typclassed-based codecs, but it's native for `scalapb` codegen.

Closes #25

### CODE REVIEW

**Comment by catostrophe** [comment]
cc @ybasket

**Review by ybasket — APPROVED** [review]
Not a fan of json4s, but as users don't interact with it and it does the job, it seems to be reasonable choice (until circe has configurability again).

Looks good to me!

**Comment by catostrophe** [comment]
P.S. custom formatters for Span and Link are needed because there's no legal way to override an encoder for ByteString.

**Review by janstenpickle — APPROVED** [review]

**Comment by catostrophe** [comment]
One test failed on Double comparison. It's a known issue, so I merge.

**Pull request merged**
